# Site settings
title: Portál o datech České republiky

description: Portál o datech a Národní katalog otevřených dat České republiky

baseurl: "" # the subpath of your site, e.g. /blog.
url: "https://data.gov.cz" # the base hostname & protocol for your site

# Build settings
excerpt_separator: <!--more-->

timezone: Europe/Prague
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

langs:
  en:
    cs: česky
    flag: /images/flag-en.svg
  cs:
    en: English
    flag: /images/flag-cs.svg

collections:
  clanky:
    output: true
    permalink: /články/:path

app_registration_form: https://forms.office.com/e/mK4wLvrww4
suggestion_form: https://forms.office.com/e/UuwD7UBnRG

# Path to design-system distribution directory, must not end with '/'.
design_system_assets: /assets/design-system
