# Site settings
title: Otevřená data České republiky

description: Portál otevřených dat České republiky
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://data.gov.cz" # the base hostname & protocol for your site

# Build settings
excerpt_separator: <!--more-->

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

langs:
  en:
    cs: česky
    flag: /images/flag-en.png
  cs:
    en: English
    flag: /images/flag-cs.png

collections:
  clanky:
    output: true
    permalink: /články/:path